// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.DataAccess.Local.SQLServer.Models;

public partial class STOCK_POSITION
{
    public int ID { get; set; }

    public string CompanyName { get; set; }

    public string Ticker { get; set; }

    public int Shares { get; set; }

    public double WeightPercent { get; set; }

    /// <summary>
    /// Stored with 0 hours, 0 minutes and 0 seconds as a hack
    /// </summary>
    public DateTime Date { get; set; }
}