// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Project.DataAccess.Local.SQLServer.Models;

public partial class SWQualityProjectContext : DbContext
{
    public SWQualityProjectContext(DbContextOptions<SWQualityProjectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<STOCK_POSITION> STOCK_POSITION { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<STOCK_POSITION>(entity =>
        {
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Date)
                .HasComment("Stored with 0 hours, 0 minutes and 0 seconds as a hack")
                .HasColumnType("date");
            entity.Property(e => e.Ticker)
                .IsRequired()
                .HasMaxLength(10);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}